package plugin

import (
	"log"

	"github.com/bazelbuild/bazel-gazelle/rule"
)

// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (e *BobExtension) Kinds() map[string]rule.KindInfo {
	log.Printf("Kinds() - NOT IMPLEMENTED\n")
	return nil
}

// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (e *BobExtension) Loads() []rule.LoadInfo {
	log.Printf("Loads() - NOT IMPLEMENTED\n")
	return nil
}
