package plugin

import (
	"github.com/bazelbuild/bazel-gazelle/rule"
)

var bobKinds = map[string]rule.KindInfo{
	"filegroup": {
		NonEmptyAttrs:  map[string]bool{"srcs": true},
		MergeableAttrs: map[string]bool{"srcs": true},
	},
	"bool_flag": {
		NonEmptyAttrs: map[string]bool{
			"name":                  true,
			"build_setting_default": true,
		},
		MergeableAttrs: map[string]bool{"build_setting_default": true},
	},
	"string_flag": {
		NonEmptyAttrs: map[string]bool{
			"name":                  true,
			"build_setting_default": true,
		},
		MergeableAttrs: map[string]bool{"build_setting_default": true},
	},
	"int_flag": {
		NonEmptyAttrs: map[string]bool{
			"name":                  true,
			"build_setting_default": true,
		},
		MergeableAttrs: map[string]bool{"build_setting_default": true},
	},
	"config_setting": {
		NonEmptyAttrs:  map[string]bool{"name": true},
		MergeableAttrs: map[string]bool{"flag_values": false},
	},
	"selects.config_setting_group": {
		NonEmptyAttrs: map[string]bool{"name": true},
		MergeableAttrs: map[string]bool{
			"match_all": true,
			"match_any": true,
		},
	},
	"cc_library": {
		NonEmptyAttrs: map[string]bool{
			"srcs": true,
			"hdrs": true,
			"deps": true,
		},
		MergeableAttrs: map[string]bool{
			"srcs":          true,
			"hdrs":          true,
			"local_defines": true,
			"defines":       true,
			"copts":         true,
			"alwayslink":    true,
			"linkstatic":    true,
		},
		SubstituteAttrs: map[string]bool{
			"srcs": true,
			"hdrs": true,
			"deps": true,
		},
		ResolveAttrs: map[string]bool{
			"deps": true,
		},
	},
}

var bobLoads = []rule.LoadInfo{
	{
		Name: "@bazel_skylib//rules:common_settings.bzl",
		Symbols: []string{
			"bool_flag",
			"string_flag",
			"int_flag",
		},
	},
	{
		Name: "@bazel_skylib//lib:selects.bzl",
		Symbols: []string{
			"selects",
		},
	},
}

// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (e *BobExtension) Kinds() map[string]rule.KindInfo {
	return bobKinds
}

// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (e *BobExtension) Loads() []rule.LoadInfo {
	return bobLoads
}
