load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "74d544d96f4a5bb630d465ca8bbcfe231e3594e5aae57e1edbf17a6eb3ca2506",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "278b7ff5a826f3dc10f04feaf0b70d48b68748ccd512d7f98bf442077f043fe3",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.41.0/rules_go-v0.41.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.41.0/rules_go-v0.41.0.zip",
    ],
)

http_archive(
    name = "bazel_gazelle",
    patch_args = [
        "-p1",
    ],
    patches = [
        "//patches:gazelle/0001-Add-SortedStrings-and-UnsortedStrings-expression-val.patch",
        "//patches:gazelle/0002-Add-the-new-Merger-interface.patch",
        "//patches:gazelle/0003-Implement-Merge-for-SortedStrings-UnsortedStrings.patch",
        "//patches:gazelle/0004-Expose-the-MergeList-MergeDict-helpers.patch",
        "//patches:gazelle/0005-fix-correct-rule-s-kind-stmt.patch",
    ],
    sha256 = "29218f8e0cebe583643cbf93cae6f971be8a2484cdcfa1e45057658df8d54002",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.32.0/bazel-gazelle-v0.32.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.32.0/bazel-gazelle-v0.32.0.tar.gz",
    ],
)

rules_python_version = "0.18.1"

http_archive(
    name = "rules_python",
    sha256 = "29a801171f7ca190c543406f9894abf2d483c206e14d6acbd695623662320097",
    strip_prefix = "rules_python-{}".format(rules_python_version),
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/{}.tar.gz".format(rules_python_version),
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")  # keep

go_rules_dependencies()

load("//:deps.bzl", "go_dependencies")

# gazelle:repository_macro deps.bzl%go_dependencies
go_dependencies()

# 1.18 for latest rules_go and Gazelle.
go_register_toolchains(version = "1.18")

gazelle_dependencies()

local_repository(
    name = "bob",
    path = "..",
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "config_deps",
    requirements_lock = "@bob//config_system:requirements_lock.txt",
)

load("@config_deps//:requirements.bzl", "install_deps")

install_deps()

# keep
go_repository(
    name = "com_github_google_blueprint",
    commit = "6957a46d",
    importpath = "github.com/google/blueprint",
    patch_args = ["-p1"],
    patches = [
        "@bob//patches:blueprint/0001-feat-visit-modules-with-position.patch",
    ],
)
